### ISSUE TITLE
Backing device question

### ISSUE THREAD

**Issue by q3cpma** [vaeth/zram-init#20]
Hello,

sorry if this the wrong place, but after searching a bit I didn't find any information about it. Am I supposed to create a filesystem on that partition? What type should it be? Should I mount it?
Also, I didn't find any "echo huge > /sys/block/zramX/write" or "echo all > /sys/block/zramX/idle" in zram-init, why is that?

I mainly try to read https://www.kernel.org/doc/Documentation/blockdev/zram.txt to get information, to no avail.

**Comment by vaeth** [comment]
If I understand correctly, the backing device must currently be a partition; no filesystem, since the whole partition will be used. However, I never tried it myself.

The {write,idle} features are relatively new and not yet supported by zram-init. Maybe when I find time, I will prepare a new release with these features, but no promise yet.

**Comment by q3cpma** [comment]
But without those features, what's the difference with having a traditional
swap with a lower priority? It's still compressed on disk and that's it?

**Comment by vaeth** [comment]
The main point of the backing device is that you don't get errors if the data cannot be compressed well so that you are actually running out of space. For a non-swap-disk you get in this case an obvious problem, probably read- or write-errors. I do not know how well swap can tackle such a situation; I would not rely on it on a real production system.

**Comment by vaeth** [comment]
v9.0 contains support for the new features
