### ISSUE TITLE
zram1 in /tmp not possible?

### ISSUE THREAD

**Issue by p0txky** [vaeth/zram-init#37]
mkfs.ext4: Invalid argument while setting blocksize; too small for device

mkfs.ext4 /dev/zram1 failed

**Comment by p0txky** [comment]
> mkfs.ext4: Invalid argument while setting blocksize; too small for device
> 
> mkfs.ext4 /dev/zram1 failed

On artix linux openrc btw

**Comment by vaeth** [comment]
> mkfs.ext4: Invalid argument while setting blocksize; too small for device

Probably the specified combination of inodes, iratio, blocksize and total size of the device makes no sense.

**Comment by p0txky** [comment]
Using only 1 device pointing to zram0, I think that most linux distro uses /var/tmp.

**Comment by vimtoe** [comment]
I am having the exact same problem here too, unfortunately.
How was this problem fixed @mpotane  @vaeth ???
My device has both `/tmp` and `/var/tmp` if that helps??
I am on Alpine Linux (latest build).

**Comment by vaeth** [comment]
It is up to you to specify the blocksize or other parameters appropriately in the configuration. The script is only a helper to pass these parameters and intentionally does noi checking.

**Comment by Unixware** [comment]
for what it's worth: 
I ran into this exact error on Alpine Linux and found the root cause.

In the default configuration file, this line makes no sense  (under the /tmp configuration)

blck1=1024 # the default blocksize of 4096

The text comment admits the default is 4096, but the code line actively forces it to a way smaller one (1024) 

Commenting out or deleting the blck1=1024 line completely fixes the issue. 
It allows the system to use the proper 4096 default, and the drive formats and mounts perfectly.
